package com.johndeweydev.awps.usbserial;

public enum UsbSerialStatus {
  ALREADY_CONNECTED,
  DEVICE_NOT_FOUND,
  DRIVER_NOT_FOUND,
  PORT_NOT_FOUND,
  DRIVER_SET,
  HAS_USB_PERMISSION,
  NO_USB_PERMISSION,
  SUCCESSFULLY_CONNECTED,
  FAILED_TO_CONNECT,
  FAILED_OPENING_DEVICE,
  UNSUPPORTED_PORT_PARAMETERS
}
